### ISSUE TITLE
bug: column collations should be ignored during SQL type comparisons (SQL Server)

### ISSUE THREAD

**Issue by radbrt** [meltano/sdk#1125]
### Singer SDK Version

0.11.1

### Python Version

3.10

### Bug scope

Targets (data type handling, batching, SQL object generation, etc.)

### Operating System

Mac

### Description

SQL Server target: Initial load of a table with a varchar column works nicely, but on second write, the loader fails with a ValueError, after attempting to change column types. In the example, a PG source table with a VARCHAR(64) column:

`ValueError: Unable to merge sql types: VARCHAR(64) COLLATE "SQL_Latin1_General_CP1_CI_AS", VARCHAR(64)`

My interpretation is that the target initially ran a create table statement with a VARCHAR(64) column, SQL Server added the collation as a detail, but when inserting again the target interprets varchar with the added collation as a different column type than VARCHAR(64) and tries to alter it, but fails.

An ugly fix is to explicitly declare the collation on table creation: https://github.com/radbrt/target-mssql/blob/37544ad6306095b66bef9f01d35211f486b9bf77/target_mssql/sinks.py#L262

**Comment by BuzzCutNorman** [comment]
The function that is causing the error is `merge_sql_types()` from the `SQLConnector` class.  It has exhausted the simple checks it knows how to do.  `merge_sql_types()` gets called from `_adapt_column_type()`.  PR #898 has info about the function.

cc: @kgpayne @aaronsteers

**Comment by aaronsteers** [comment]
@BuzzCutNorman - On thinking about this more, I think we just need to compare types in a way that completely ignores collation.

The argument is that collation (sorting, for example) is a DB-level abstraction and the sync operation (a data replication job) should only be concerned with the fidelity of the data itself, not the upstream systems' sort and/or equality comparison behaviors.

Even if we could honor the upstream collation preferences, the argument goes, we probably _shouldn't_. Therefor, the target developer can choose to customize those or use the system defaults - but we should find a way to systemically ignore them during type comparisons.

Wdyt?

**Comment by aaronsteers** [comment]
Related:

- https://github.com/MeltanoLabs/target-snowflake/issues/4

**Comment by BuzzCutNorman** [comment]
@aaronsteers I agree with what you said.  There are some things that get a little muddled during the table alter/merge process.
> The argument is that collation (sorting, case sensitivity, accent sensitivity, etc.) is a DB-level abstraction and the sync operation (a data replication job) should only be concerned with the fidelity of the data itself, not the upstream systems' sort and/or equality comparison behaviors.

In the way this currently works we place the stream schema and the actual pulled table schema in and check to see which one is the best option via the `merge_sql_types` and `_sort_types`.  In all honesty I don't know if the issue is coming from the stream schema which I kind of doubt or the target column info we gather via `_get_column_type` .  All column types passed through `_sort_types` and best match bubbles to the top.  Making the process easier to follow for debugging purposes would go along way.

> Even if we could honor the upstream collation preferences, the argument goes, we probably shouldn't. Therefor, the target developer can choose to customize those or use the target database's defaults - but we should find a way to systemically ignore them during type comparisons - because the JSON dataset arriving from source shouldn't be transmitting those preferences from source system to the target system.

I agree with this and that was the original intent of the process.  The issue came when the process started trying to change any existing character-based column to a max size even when the current one could fit the stream character length.  I was trying to get to a point that if a target character column was of adequate size to allow stream data to be inserted without truncation it wouldn't try to alter the column.  I couldn't figure out how to get both column lengths without doing string manipulation which I thought might blow up later.  If we have both stream and target lengths we could go back to evaluating generic types and simply check what scenario the column lengths fit into. 

I need to look over the target-snowflake type checking that @kgpayne  put in place and give it try to see if it resolves the above character sizing that stumped me.

**Comment by cwegener** [comment]
Random link after just having caught up on the discussion on this topic during office hours.

Is this related to this open issue? https://github.com/sqlalchemy/sqlalchemy/issues/6511

**Comment by BuzzCutNorman** [comment]
@radbrt what PG tap are you using ?

**Comment by radbrt** [comment]
@BuzzCutNorman I use the default one. I added my testing setup to my github: https://github.com/radbrt/rmme_mssql

**Comment by BuzzCutNorman** [comment]
@radbrt Thanks for putting all that online.  I noticed you were testing on mssql 2022 express.  When you get a chance could you try using the `image: mcr.microsoft.com/mssql/server:2017-latest) ` and `MSSQL_PID: "Developer"` and let me know what you get.

**Comment by BuzzCutNorman** [comment]
@radbrt I believe I figure it out.  The key was the tap you were using.  Pipelinewise tap-postgres does a good job of sending the length of the fields.  The `merge_sql_types` function only knew how to deal with instances in which one of the character column had `null` or `0` lengths.  Both values are converted to `max` by SQLA so the function was set to prefer them.  In your example there is no max there is only `64` or `64` so the function threw up it hand and said "I don't know".  if we change line 752 in sdk version 11 that your tap uses from `if (opt_len is None) or (opt_len == 0):` to `if (opt_len is None) or (opt_len == 0) or (opt_len >= current_type.length):` it can make a decision and it keeps the current field type.  The Collation difference triggered `merge_sql_types` fucntion to be called but the length of the field was the cause of it not making a decision.

cc @aaronsteers @kgpayne

**Comment by BuzzCutNorman** [comment]
@aaronsteers @edgarrmondragon WDYT about me breaking this into two issue and PRs? First create a new issue for the length case and a PR with the code I mentioned earlier.  Second create a PR connected to this issue to rework `adapt_column_type`, `merge_sql_types`, and `_sort_types` to drop collation and make the process clearer to follow.

**Comment by aaronsteers** [comment]
@BuzzCutNorman, Approaching as two PRs sounds good to me! 👍

**Comment by BuzzCutNorman** [comment]
I found that collation is being grabbed by `sqlalchemy.inspect.get_columns()` that is found in `SQLConnector.get_table_columns()`.  Collation is pulled when inspecting mssql, mysql, mariadb as far as I can tell.  for VARCHAR and NVARCHAR is optional. 

@aaronsteers @edgarrmondragon what would you think about setting this to `None` if present when `get_table_columns` is run? I was playing with `hasattr` and `setattr` to set collation to `None`.
