### ISSUE TITLE
bug: Record flattening converts objects to strings at the max depth

### ISSUE THREAD

**Issue by edgarrmondragon** [meltano/sdk#1400]
### Singer SDK Version

0.19.0

### Python Version

NA

### Bug scope

Taps (catalog, state, stream maps, etc.)

### Operating System

NA

### Description

With config

```json
{
  "flattening_enabled": true,
  "flattening_max_depth": 1
}
```

This record

```json
{
    "type": "RECORD",
    "stream": "mystream",
    "record": {
        "email": "alice@example.com",
        "count": 21,
        "user": {
            "id": 1,
            "sub": {
                "num": 1
            }
        }
    },
    "time_extracted": "2022-01-01T00:00:00+00:00"
}
```

is flattened into

```json
{
    "type": "RECORD",
    "stream": "mystream",
    "record": {
        "email": "alice@example.com",
        "count": 21,
        "user__id": 1,
        "user__sub": "{\"num\": 1}"
    },
    "time_extracted": "2022-01-01T00:00:00+00:00"
}
```

Note how `user__sub` is a string. The type of `object` is preserved in the schema message, though.

See the snapshots:

https://github.com/meltano/sdk/blob/89adc1ba5bbb7efed9f94c50aa36ee9831d523e6/tests/snapshots/mapped_stream/flatten_depth_1.jsonl#L1

https://github.com/meltano/sdk/blob/89adc1ba5bbb7efed9f94c50aa36ee9831d523e6/tests/snapshots/mapped_stream/flatten_depth_1.jsonl#L2

**Comment by aaronsteers** [comment]
@edgarrmondragon - Definitely a bug, since transformed node data doesn't match the outputted SCHEMA message.

Do you know if `pipelinewise` or other taps/targets will treat this as stringified JSON (as we've done with the record data) or as a JSON object (as we've done with the SCHEMA message)? Perhaps this feature primarily exists in the target layer, where that distinction is less of an issue?

Since targets can and should be able to serialize and/or stringify object-typed top level properties, I think I lean towards _not_ stringifying the object, but instead passing along as an object. (Targets then would decide whether to stringify or store as an object/json column.

**Comment by edgarrmondragon** [comment]
> Do you know if `pipelinewise` or other taps/targets will treat this as stringified JSON (as we've done with the record data) or as a JSON object (as we've done with the SCHEMA message)? Perhaps this feature primarily exists in the target layer, where that distinction is less of an issue?

@aaronsteers I only tested this with `target-sqlite` and it fails during the JSON schema validation, and I guess other targets behave similarly.

> I think I lean towards not stringifying the object, but instead passing along as an object - in line with what you've written above in the bug report. (Targets then would decide whether to stringify or store as an object/json column.

I agree 👍

**Comment by edgarrmondragon** [comment]
Still relevant
